export * from './Header/Header';
export * from './Movies/Movies';
export * from './MovieOneCard/MovieOneCard';
export * from './Genres/Genres';
export * from './Genre/Genre';
export * from './MovieByGenre/MovieByGenre';
export * from './MovieById/MovieById';
export * from './Favorite/Favorite';
export * from './Search/Search';